app1/urls.py
from django.urls import path
from .import views

urlpatterns = [
    
    path("info/",views.order_form,name='inquary_form'),
    path("show_info/",views.show_order,name='show_info'),
    path("info_update/<int:id>/",views.update_order,name='update_info'),
    path("info_delete/<int:id>/",views.delete_order,name='delete_info'),

]

project1/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
]

Product/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
    Product_name = models.CharField(max_length = 150)
    price = models.IntegerField(default=0)
    Qty = models.IntegerField(default=0)
    total_price = models.IntegerField(default=0)

app1/models.py
from django.db import models
from Product.models import Product
# Create your models here.

class orderform(models.Model):
    customer = models.CharField(max_length=20)
    Product = models.ForeignKey("Product.Product",on_delete=models.CASCADE)

    def __str__(self):
        return self.name

Product/views.py
from django.shortcuts import render

# Create your views here.

app1/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import orderform

# Create your views here.

def index(request):
    return HttpResponse('hello world')

def order_form(request):
    if request.POST:
        obj = orderform()
        obj.customer = request.POST['customer']
        obj.product = request.POST['product']
        obj.price = request.POST['price']
        obj.Qty = request.POST['Qty']
        obj.total_price = request.POST['total_price']
        obj.save()
        return redirect('show_info')

    return render(request,'order_form.html')

def show_order(request):
    data = orderform.objects.all()
    return render(request,'order_show.html',{'data':data})

def update_order(request,id):
    obj = orderform.objects.get(id=id)
    if request.POST:
        obj.customer = request.POST['customer']
        obj.product = request.POST['product']
        obj.price = request.POST['price']
        obj.Qty = request.POST['Qty']
        obj.total_price = request.POST['total_price']
        obj.save()
        return redirect('show_info')

    return render(request,'order_form.html',{'data':obj})

def delete_order(request,id):
    obj = orderform.objects.get(id=id)
    obj.delete()
    return redirect('show_info')



app1/templates/order_form.html
<div class="order-form">
    <form method="POST">
        {% csrf_token %}
        <label>Customer: </label>
        <input type="text" name="customer" id="id_customer" value="{{ data.customer }}"><br>
        <label>Product: </label>
        <input type="text" name="product" id="id_product" value="{{ data.product }}"><br>
        <label>Price: </label>
        <input type="text" name="price" id="id_price" value="{{ data.price }}"><br>
        <label>Qty: </label>
        <input type="text" name="Qty" id="id_Qty" value="{{ data.Qty }}"><br>
        <label>Total price: </label>
        <input type="text" name="total_price" id="id_total_price" value="{{ data.total_price }}"><br>
        
        <input type="submit" value="submit" class="text-uppercase">
    </form>
</div>

app1/templates/order_show.html
{% for i in data reversed %}

    <h1>customer name : {{ i.customer }}</h1>
    <h1>product : {{ i.product }}</h1>
    <h1>price : {{ i.price }}</h1>
    <h1>Qty : {{ i.Qty }}</h1>
    <h1>Total price : {{ i.total_price }}</h1>

    <a href="{% url 'update_info' i.id %}">Update</a>
    <a href="{% url 'delete_info' i.id %}">Delete</a><br><br>

{% endfor %}